version: '3'

services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    entrypoint: >
      python -c "import ccxt, sys; ccxt.indodax.has.update({'fetchOHLCV': True, 'fetchMyTrades': True, 'fetchTickers': True, 'watchOHLCV': True}); sys.argv[0] = 'freqtrade'; from freqtrade.main import main; main()"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy FatQulStrategy
    env_file:
      - .env

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: fatqul_dashboard
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - "./dashboard:/app"
      - "./user_data:/app/user_data:ro"  # Read-only access to freqtrade DB and logs
    depends_on:
      - freqtrade
    env_file:
      - .env

  whatsapp-bot:
    build:
      context: ./whatsapp_bot
      dockerfile: Dockerfile
    container_name: fatqul_whatsapp
    restart: unless-stopped
    volumes:
      - "./whatsapp_bot:/app"
      - "./user_data:/app/user_data:ro" # Read-only access to freqtrade DB
    depends_on:
      - freqtrade
    env_file:
      - .env
